### ISSUE TITLE
Phase 1 prompts and responses

### ISSUE THREAD

**Issue by hucklebridge** [fjebaker/global-game-jam-2022#14]

**Comment by hucklebridge** [comment]
You are offered wine,SIP,DRINK,DOWN BOTTLE
You are offered cake,NIBBLE,EAT SLICE,EAT ALL
You are invited to conga,BACK,MIDDLE,FRONT
Things get rowdy,JEER,TUSSLE,FIGHT
A round of shots starts,TAKE ONE,TAKE TWO,TAKE SIX
Karaoke starts,HUM ALONG,HUM & DANCE,SING
Never have I ever starts,LISTEN IN,ASK QUESTION,PLAY ALONG
Someone passes out,LAUGH,TAKE PHOTO,DRAW ON FACE
Someone's wearing a mask,POINT & LAUGH,COUGH ON THEM,YANK IT OFF

**Comment by jwiggins** [comment]
I like these
