### ISSUE TITLE
Phase 2 prompts and responses

### ISSUE THREAD

**Issue by hucklebridge** [fjebaker/global-game-jam-2022#17]

**Comment by hucklebridge** [comment]
RESPONSES (always the same):

TELL TRUTH
WAFFLE
CHANGE TOPIC

**Comment by hucklebridge** [comment]
QUESTIONS (chosen at random):

Last night location?,Followed lockdown?,Social distancing?,No parties?,Telling the truth?,Working from home?,Quiz happened?,No birthday celebration?,Same rules as us?,Out drinking?

**Comment by jwiggins** [comment]
Didn't we want something about Peppa Pig here?

**Comment by hucklebridge** [comment]
Last night location?,Followed lockdown?,Social distancing?,No parties?,Telling the truth?,Working from home?,Quiz happened?,No birthday celebration?,Same rules as us?,Out drinking?,Been to Peppa Pig world?
