### ISSUE TITLE
Boris Johnson asset

### ISSUE THREAD

**Issue by hucklebridge** [fjebaker/global-game-jam-2022#2]

**Comment by Shellywell123** [comment]
![pixil-gif-drawing (1)](https://user-images.githubusercontent.com/44142139/151623223-7c62b0f4-ae13-4c1d-b566-6175e8730d10.gif)
![pixil-gif-drawing](https://user-images.githubusercontent.com/44142139/151623226-a3520012-ef2c-4c39-985a-2f484c73c5f2.gif)

**Comment by jwiggins** [comment]
I've got the version of this from Discord added in #12. Can you convert the top animation to a PNG sprite sheet?

**Comment by Shellywell123** [comment]
![Pixilart Sprite Sheet (1) (1)](https://user-images.githubusercontent.com/44142139/151635413-a5b8e4f9-9f61-432a-aeb5-136050835238.png)

**Comment by jwiggins** [comment]
Still something weird with this one:
```
Error processing src/assets/boris_white.png: unrecognised content at end of stream
```
