### ISSUE TITLE
Guest assets

### ISSUE THREAD

**Issue by hucklebridge** [fjebaker/global-game-jam-2022#5]

**Comment by hucklebridge** [comment]
Do we want to be able to directly substitute the Boris Johnson character #2 or devise entirely different assets for each character?

**Comment by hucklebridge** [comment]
Do we want these characters to be unlocked after receiving certain scores? #4

**Comment by Shellywell123** [comment]
![Pixilart Sprite Sheet (3)](https://user-images.githubusercontent.com/44142139/151629748-6c3966cf-d164-441e-b7c2-96715ac9998e.png)

![pixil-gif-drawing (3)](https://user-images.githubusercontent.com/44142139/151629751-827678a0-e197-404e-ad1e-ce80db3f4742.gif)

**Comment by jwiggins** [comment]
Error processing /Users/john/source/Global Game Jam/2022/src/assets/guest.png: 
Too many colors: maximum is 4. The previous colors were:
- (R: 0, G: 0, B: 0, A: 0); first seen at (0, 0)
- (R: 0, G: 0, B: 0, A: 255); first seen at (3, 0)
- (R: 158, G: 158, B: 158, A: 255); first seen at (3, 1)
- (R: 250, G: 250, B: 250, A: 255); first seen at (23, 11)
The first occurrence of another color is at (24, 12) and has the value of (R: 236, G: 239, B: 241, A: 255)

**Comment by Shellywell123** [comment]
![Pixilart Sprite Sheet (3) (1)](https://user-images.githubusercontent.com/44142139/151635476-bf120951-6635-4ace-b27c-25c29bc6a75a.png)
